# Generated by Django 3.2.4 on 2021-06-29 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='Photo',
            field=models.ImageField(default='', upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='signup',
            name='Age',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='signup',
            name='Email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='signup',
            name='Name',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='signup',
            name='Password',
            field=models.CharField(default='', max_length=8),
        ),
    ]
